# Generated by Django 5.2.4 on 2025-08-14 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_image', models.ImageField(upload_to='images/restaurants/')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('notes', models.TextField()),
                ('createdon', models.DateTimeField(auto_now_add=True)),
                ('updatedon', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.city')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.restaurantowner')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RestaurantFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=50)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('image', models.ImageField(upload_to='images/restaurant_food/')),
                ('notes', models.TextField()),
                ('createdon', models.DateTimeField(auto_now_add=True)),
                ('updatedon', models.DateTimeField(auto_now=True)),
                ('is_available', models.BooleanField(default=True)),
                ('category', models.CharField(choices=[('main', 'Main Course'), ('side', 'Side Dish'), ('drink', 'Drink'), ('dessert', 'Dessert')], default='main', max_length=20)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='images/default/default.jpg', upload_to='images/restaurant_tables/')),
                ('table_number', models.CharField(max_length=10, unique=True)),
                ('seats', models.PositiveIntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=50)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='restaurants.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='TableReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateField()),
                ('reservation_time', models.TimeField()),
                ('guests', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('createdon', models.DateTimeField(auto_now_add=True)),
                ('updatedon', models.DateTimeField(auto_now=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='restaurants.restauranttable')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.tourist')),
            ],
        ),
    ]
