# Generated by Django 5.2.4 on 2025-08-14 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gallery', '0001_initial'),
        ('places', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('history', models.TextField()),
                ('month_of_celebration', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default='January', max_length=20)),
                ('category', models.CharField(choices=[('cultural', 'Cultural'), ('religious', 'Religious'), ('music', 'Music'), ('harvest', 'Harvest'), ('other', 'Other')], default='cultural', max_length=20)),
                ('cover_image', models.ImageField(upload_to='festival_covers/')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('creatdon', models.DateTimeField(auto_now_add=True)),
                ('updatedon', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.city')),
                ('gallery', models.ManyToManyField(blank=True, related_name='festivals', to='gallery.media')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.festivalowner')),
            ],
        ),
    ]
